FROM python


WORKDIR /code


COPY ./fastapi/requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./fastapi /code/fastapi/


CMD ["fastapi", "dev", "fastapi/main.py", "--host", "0.0.0.0", "--port", "8000"]