services:
  fastapi:
    build:
      dockerfile: dockerfile-fastapi
    container_name: fastapi_app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}

  postgres:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  db_data:
