import json
from typing import Annotated

from fastapi import FastAPI, File, UploadFile

app = FastAPI()

@app.post("/upload-sarif/")
async def upload_sarif_file(sarif_file: UploadFile = File(description="File generated by CodeQL")):
    contents = await sarif_file.read()
    sarif_data = contents.decode("utf-8")
    sarif_json = json.loads(sarif_data)
        
    # Store SARIF JSON in database
    return {"sarif": sarif_json}