import json
import os
from typing import Annotated
from fastapi import FastAPI, File, UploadFile
from databases import Database


# Initialize FastAPI and Database
app = FastAPI()
DATABASE_URL = os.getenv('DATABASE_URL')
database = Database(DATABASE_URL)

# Connect to the database on startup
@app.on_event("startup")
async def startup():
    await database.connect()

# Disconnect from the database on shutdown
@app.on_event("shutdown")
async def shutdown():
    await database.disconnect()

@app.post("/upload-sarif/")
async def upload_sarif_file(sarif_file: UploadFile = File(description="File generated by CodeQL")):
    contents = await sarif_file.read()
    sarif_data = contents.decode("utf-8")
    sarif_json = json.loads(sarif_data)
    
    runs = sarif_json['runs'][0]
    results = runs['results']
    rules = runs['tool']['driver']['rules']
    print(results)
    print(rules)

    # TODO: Store SARIF JSON in database
    return {"sarif": sarif_json}